### ISSUE TITLE
cannot pull from registry

### ISSUE THREAD

**Issue by hududed** [FAIRDataPipeline/pySimpleModel#5]
```
❯ fair pull simpleModel/ext/SEIRSconfig.yaml
fair run simpleModel/ext/SEIRSconfig.yaml

Error: Cannot perform pull from registry 'origin' as the server does not exist. Expected response from 'http://127.0.0.1:8001/api/'.
Is your FAIR repository configured correctly?
Traceback (most recent call last):
  File "/home/hud/projects/pySimpleModel/simpleModel/ext/SEIRSModelRun.py", line 16, in <module>
    initial_parameters = pipeline.link_read(handle, "SEIRS_model/parameters")
  File "/home/hud/.pyenv/versions/3.10.7/lib/python3.10/site-packages/data_pipeline_api/link.py", line 158, in link_read
    id=int(fdp_utils.extract_id(data_product_response[0]["object"])),
IndexError: list index out of range
Error: Executed 'run' command failed with exit code 1
```

Getting the error - Is this a python version issue?

**Comment by LiamPattinson** [comment]
I also ran into this problem, and though I managed to fix it, it just led to a brand new problem I'm unable to solve. I think the recommendation to run `fair init --ci` is the culprit, as this sets a lot of default configuration details that can't be easily changed, including setting the registry port to 8001, while `fair registry start` uses port 8000 by default.

- Call `fair purge` to remove the local `.fair` folder. To remove any of the user data which was set by calling `fair init --ci` you have to go quite a bit further; I had to `rm -rf` my `~/.fair` folder and reinstall the registry to fix it completely.
- Restart your registry using `fair registry stop --force`, `fair registry start`. Note the address it's running on and the location of the token.
- Call `fair init` without the `--ci` tag. Enter the address and token of the registry when prompted. If you started fresh, you'll also need to set things like user name/email. I set the remote api/data to `http://127.0.0.1:8000/api/` and `http://127.0.0.1:8000/data/`, but I'm unsure if this is correct.

On running `fair pull simpleModel/ext/SEIRSconfig.yaml`, I now get the following error:

```
Error: Failed to make registry API request 'https://127.0.0.1:8000/api/namespace/'
Is this remote correct and the server running?
```

I think the issue is that it's making a request using `https` instead of `http`, as `http://127.0.0.1:8000/api/namespace` appears to work just fine if you open it in a browser. Is this a bug, or have I just configured something wrong? I haven't found anything in the documentation or existing issues about it. I followed some online guides for getting `https://localhost` to work, but that didn't seem to help.

**Comment by LiamPattinson** [comment]
Never mind, I managed to fix this too. It turned out to be a self-inflicted error I'd introduced while experimenting with `SEIRSconfig.yaml`. It's now running fine for me. I think the advice in the README needs to be updated so that it doesn't recommend `fair init --ci`, and otherwise this would be resolved.
